name: Hub Trigger

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build stretch
      - run: docker build stretch/slim
      - run: docker build buster
      - run: docker build buster/slim
      - run: docker build alpine3.12
      - run: |
          curl -sS -H "Content-Type: application/json" --data '{"build": true}' -X POST \
            https://hub.docker.com/api/build/v1/source/23e76a6c-9b2f-4012-a2eb-32128b053afb/trigger/${{ secrets.TRIGGER_TOKEN }}/call/
